In [2]:
import csv
with open("winequality-red.csv", 'r') as f:
   wines = list(csv.reader(f, delimiter=";"))
print(wines[:3])
[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality'], ['7.4', '0.7', '0', '1.9', '0.076', '11', '34', '0.9978', '3.51', '0.56', '9.4', '5'], ['7.8', '0.88', '0', '2.6', '0.098', '25', '67', '0.9968', '3.2', '0.68', '9.8', '5']]

[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality'], ['7.4', '0.7', '0', '1.9', '0.076', '11', '34', '0.9978', '3.51', '0.56', '9.4', '5'], ['7.8', '0.88', '0', '2.6', '0.098', '25', '67', '0.9968', '3.2', '0.68', '9.8', '5']]


[['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol',
  'quality'],
 ['7.4',
  '0.7',
  '0',
  '1.9',
  '0.076',
  '11',
  '34',
  '0.9978',
  '3.51',
  '0.56',
  '9.4',
  '5'],
 ['7.8',
  '0.88',
  '0',
  '2.6',
  '0.098',
  '25',
  '67',
  '0.9968',
  '3.2',
  '0.68',
  '9.8',
  '5']]

In [3]:
type(wines)


list

In [4]:
print(wines[:3])


[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality'], ['7.4', '0.7', '0', '1.9', '0.076', '11', '34', '0.9978', '3.51', '0.56', '9.4', '5'], ['7.8', '0.88', '0', '2.6', '0.098', '25', '67', '0.9968', '3.2', '0.68', '9.8', '5']]


In [5]:
#for item in wines[1:]:
    #print(item[-1])
len(wines)

1600

In [6]:
# List comprehension
qualities = [float(item[-1]) for item in wines[1:]]

sum(qualities) / len(qualities)

5.6360225140712945

Although we were able to do the calculation we wanted, the code is fairly complex, and it won't be fun to have to do something similar every time we want to compute a quantity. Luckily, we can use NumPy to make it easier to work with our data.

In [7]:
import numpy as np
wines = np.array(wines[1:], dtype=np.float)
wines


array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [8]:
wines.shape


(1599, 12)

Loding the data using numpy library

In [9]:
wines = np.genfromtxt("winequality-red.csv", delimiter=";", skip_header=1)


In [10]:
wines.shape

(1599, 12)

In [11]:
wines[2,3]


2.3

In [12]:
wines[0:3,3]


array([1.9, 2.6, 2.3])

In [13]:
wines[:3,3]


array([1.9, 2.6, 2.3])

In [14]:
wines[:,3]


array([1.9, 2.6, 2.3, ..., 2.3, 2. , 3.6])

In [15]:
wines[3,:]


array([11.2  ,  0.28 ,  0.56 ,  1.9  ,  0.075, 17.   , 60.   ,  0.998,
        3.16 ,  0.58 ,  9.8  ,  6.   ])

In [16]:
wines[:,:]


array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [17]:
wines[1,5] = 10


In [18]:
wines[:,10] = 50


In [19]:
third_wine = wines[3,:]


In [20]:
third_wine

array([11.2  ,  0.28 ,  0.56 ,  1.9  ,  0.075, 17.   , 60.   ,  0.998,
        3.16 ,  0.58 , 50.   ,  6.   ])

In [21]:
third_wine[1]


0.28

In [22]:
np.random.rand(3)


array([0.11074869, 0.37912045, 0.11573285])

In [23]:
year_one = [
    [500,505,490],
    [810,450,678],
    [234,897,430],
    [560,1023,640]
]

In [27]:
earnings = [
            [
                [500,505,490],
                [810,450,678],
                [234,897,430],
                [560,1023,640]
            ],
            [
                [600,605,490],
                [345,900,1000],
                [780,730,710],
                [670,540,324]
            ]
          ]

In [28]:
earnings.shape

AttributeError: 'list' object has no attribute 'shape'

In [29]:
earnings = np.array(earnings)
earnings[0,0,0]


500

In [30]:
earnings.shape

(2, 4, 3)

In [31]:
earnings.shape


(2, 4, 3)

In [32]:
earnings[:,0,0]


array([500, 600])

In [33]:
earnings[:,0,:]


array([[500, 505, 490],
       [600, 605, 490]])

In [34]:
wines.dtype


dtype('float64')

In [35]:
wines.astype(int)


array([[ 7,  0,  0, ...,  0, 50,  5],
       [ 7,  0,  0, ...,  0, 50,  5],
       [ 7,  0,  0, ...,  0, 50,  5],
       ...,
       [ 6,  0,  0, ...,  0, 50,  6],
       [ 5,  0,  0, ...,  0, 50,  5],
       [ 6,  0,  0, ...,  0, 50,  6]])

In [36]:
int_wines = wines.astype(int)
int_wines.dtype.name

'int64'

In [37]:
wines.astype(np.int32)

array([[ 7,  0,  0, ...,  0, 50,  5],
       [ 7,  0,  0, ...,  0, 50,  5],
       [ 7,  0,  0, ...,  0, 50,  5],
       ...,
       [ 6,  0,  0, ...,  0, 50,  6],
       [ 5,  0,  0, ...,  0, 50,  5],
       [ 6,  0,  0, ...,  0, 50,  6]], dtype=int32)

NumPy Array Operations


In [38]:
wines[:,11] + 10
#Broadcasting

array([15., 15., 15., ..., 16., 15., 16.])

In [39]:
wines[:,11] += 10
wines[:,11]

array([15., 15., 15., ..., 16., 15., 16.])

In [40]:
wines[:,11] * 2


array([30., 30., 30., ..., 32., 30., 32.])

In [41]:
wines[:,11] + wines[:,11]


array([30., 30., 30., ..., 32., 30., 32.])

In [42]:
wines[:,10] * wines[:,11]


array([750., 750., 750., ..., 800., 750., 800.])

In [43]:
wines * np.array([1,2])


ValueError: operands could not be broadcast together with shapes (1599,12) (2,) 

In [44]:
array_one = np.array(
    [
        [1,2],
        [3,4]
    ]
)
array_two = np.array([4,5])

array_one + array_two

array([[5, 7],
       [7, 9]])

In [45]:
rand_array = np.random.rand(12)
wines + rand_array

array([[ 8.36738751,  0.76943372,  0.59222888, ...,  0.86144643,
        50.99148704, 15.39405239],
       [ 8.76738751,  0.94943372,  0.59222888, ...,  0.98144643,
        50.99148704, 15.39405239],
       [ 8.76738751,  0.82943372,  0.63222888, ...,  0.95144643,
        50.99148704, 15.39405239],
       ...,
       [ 7.26738751,  0.57943372,  0.72222888, ...,  1.05144643,
        50.99148704, 16.39405239],
       [ 6.86738751,  0.71443372,  0.71222888, ...,  1.01144643,
        50.99148704, 15.39405239],
       [ 6.96738751,  0.37943372,  1.06222888, ...,  0.96144643,
        50.99148704, 16.39405239]])

In [46]:
wines[:,11].sum()
len(wines[:,11])
wines[:,11].mean()


15.636022514071295

In [47]:
wines.sum(axis=0)
#wines.shape

array([13303.1    ,   843.985  ,   433.29   ,  4059.55   ,   139.859  ,
       25369.     , 74302.     ,  1593.79794,  5294.47   ,  1052.38   ,
       79950.     , 25002.     ])

In [48]:
wines.sum(axis=1).shape


(1599,)

In [49]:
wines.sum(axis=1)


array([125.1438 , 158.2548 , 149.899  , ..., 149.48174, 155.01547,
       141.49249])

In [50]:
wines[:,11] > 5


array([ True,  True,  True, ...,  True,  True,  True])

In [51]:
wines[:,11] == 10


array([False, False, False, ..., False, False, False])

Subsetting


In [52]:
high_quality = wines[:,11] == 6


In [53]:
high_quality

array([False, False, False, ..., False, False, False])

In [54]:
wines[high_quality,:]

array([], shape=(0, 12), dtype=float64)

In [55]:
high_quality = wines[:,11] > 7
wines[high_quality,:][:3,:]

array([[7.400e+00, 7.000e-01, 0.000e+00, 1.900e+00, 7.600e-02, 1.100e+01,
        3.400e+01, 9.978e-01, 3.510e+00, 5.600e-01, 5.000e+01, 1.500e+01],
       [7.800e+00, 8.800e-01, 0.000e+00, 2.600e+00, 9.800e-02, 1.000e+01,
        6.700e+01, 9.968e-01, 3.200e+00, 6.800e-01, 5.000e+01, 1.500e+01],
       [7.800e+00, 7.600e-01, 4.000e-02, 2.300e+00, 9.200e-02, 1.500e+01,
        5.400e+01, 9.970e-01, 3.260e+00, 6.500e-01, 5.000e+01, 1.500e+01]])

In [56]:
(wines[:,10] > 10) & (wines[:,11] > 7)

array([ True,  True,  True, ...,  True,  True,  True])

In [57]:
a = np.array([[1,2,3],[4,5,6]])

In [58]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
a[([True,True]),0:2]

array([[1, 2],
       [4, 5]])

In [60]:
high_quality_and_alcohol = (wines[:,10] > 10) & (wines[:,11] > 7)
wines[high_quality_and_alcohol,10:]

array([[50., 15.],
       [50., 15.],
       [50., 15.],
       ...,
       [50., 16.],
       [50., 15.],
       [50., 16.]])

In [61]:
high_quality_and_alcohol = (wines[:,10] > 10) & (wines[:,11] > 7)


In [62]:
high_quality_and_alcohol.shape

(1599,)

In [63]:
high_quality_and_alcohol[10:40]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [64]:
high_quality_and_alcohol = (wines[:,10] > 10) & (wines[:,11] > 7)
wines[high_quality_and_alcohol,10:] 

array([[50., 15.],
       [50., 15.],
       [50., 15.],
       ...,
       [50., 16.],
       [50., 15.],
       [50., 16.]])

In [65]:
np.transpose(wines).shape


(12, 1599)

In [66]:
wines.ravel().shape


(19188,)

In [67]:
array_one = np.array(
    [
        [1, 2, 3, 4], 
        [5, 6, 7, 8]
    ]
)

array_one.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [68]:
wines[1,:].reshape((2,6))


array([[ 7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 10.    ],
       [67.    ,  0.9968,  3.2   ,  0.68  , 50.    , 15.    ]])

In [69]:
white_wines = np.genfromtxt("winequality-white.csv", delimiter=";", skip_header=1)
white_wines.shape

(4898, 12)

In [70]:
all_wines = np.vstack((wines, white_wines))
all_wines.shape

(6497, 12)

In [71]:
np.concatenate((wines, white_wines), axis=0)


array([[7.40e+00, 7.00e-01, 0.00e+00, ..., 5.60e-01, 5.00e+01, 1.50e+01],
       [7.80e+00, 8.80e-01, 0.00e+00, ..., 6.80e-01, 5.00e+01, 1.50e+01],
       [7.80e+00, 7.60e-01, 4.00e-02, ..., 6.50e-01, 5.00e+01, 1.50e+01],
       ...,
       [6.50e+00, 2.40e-01, 1.90e-01, ..., 4.60e-01, 9.40e+00, 6.00e+00],
       [5.50e+00, 2.90e-01, 3.00e-01, ..., 3.80e-01, 1.28e+01, 7.00e+00],
       [6.00e+00, 2.10e-01, 3.80e-01, ..., 3.20e-01, 1.18e+01, 6.00e+00]])