In [75]:
import csv
with open("alcoholquality-red.csv", 'r') as f:
   alcohols = list(csv.reader(f, delimiter=";"))
print(alcohols[:3])
[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality'], ['7.4', '0.7', '0', '1.9', '0.076', '11', '34', '0.9978', '3.51', '0.56', '9.4', '5'], ['7.8', '0.88', '0', '2.6', '0.098', '25', '67', '0.9968', '3.2', '0.68', '9.8', '5']]

[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality'], ['7.4', '0.7', '0', '1.9', '0.076', '11', '34', '0.9978', '3.51', '0.56', '9.4', '5'], ['7.8', '0.88', '0', '2.6', '0.098', '25', '67', '0.9968', '3.2', '0.68', '9.8', '5']]


[['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol',
  'quality'],
 ['7.4',
  '0.7',
  '0',
  '1.9',
  '0.076',
  '11',
  '34',
  '0.9978',
  '3.51',
  '0.56',
  '9.4',
  '5'],
 ['7.8',
  '0.88',
  '0',
  '2.6',
  '0.098',
  '25',
  '67',
  '0.9968',
  '3.2',
  '0.68',
  '9.8',
  '5']]

In [2]:
type(alcohols)


list

In [3]:
print(alcohols[:3])


[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality'], ['7.4', '0.7', '0', '1.9', '0.076', '11', '34', '0.9978', '3.51', '0.56', '9.4', '5'], ['7.8', '0.88', '0', '2.6', '0.098', '25', '67', '0.9968', '3.2', '0.68', '9.8', '5']]


In [4]:
#for item in alcohols[1:]:
    #print(item[-1])
len(alcohols)

1600

In [5]:
# List comprehension
qualities = [float(item[-1]) for item in alcohols[1:]]

sum(qualities) / len(qualities)

5.6360225140712945

Although we were able to do the calculation we wanted, the code is fairly complex, and it won't be fun to have to do something similar every time we want to compute a quantity. Luckily, we can use NumPy to make it easier to work with our data.

In [6]:
import numpy as np
alcohols = np.array(alcohols[1:], dtype=np.float)
alcohols


array([[  7.4  ,   0.7  ,   0.   , ...,   0.56 ,   9.4  ,   5.   ],
       [  7.8  ,   0.88 ,   0.   , ...,   0.68 ,   9.8  ,   5.   ],
       [  7.8  ,   0.76 ,   0.04 , ...,   0.65 ,   9.8  ,   5.   ],
       ..., 
       [  6.3  ,   0.51 ,   0.13 , ...,   0.75 ,  11.   ,   6.   ],
       [  5.9  ,   0.645,   0.12 , ...,   0.71 ,  10.2  ,   5.   ],
       [  6.   ,   0.31 ,   0.47 , ...,   0.66 ,  11.   ,   6.   ]])

In [7]:
alcohols.shape


(1599, 12)

Loding the data using numpy library

In [8]:
alcohols = np.genfromtxt("alcoholquality-red.csv", delimiter=";", skip_header=1)


In [9]:
alcohols.shape

(1599, 12)

In [10]:
alcohols[2,3]


2.2999999999999998

In [11]:
alcohols[0:3,3]


array([ 1.9,  2.6,  2.3])

In [12]:
alcohols[:3,3]


array([ 1.9,  2.6,  2.3])

In [13]:
alcohols[:,3]


array([ 1.9,  2.6,  2.3, ...,  2.3,  2. ,  3.6])

In [14]:
alcohols[3,:]


array([ 11.2  ,   0.28 ,   0.56 ,   1.9  ,   0.075,  17.   ,  60.   ,
         0.998,   3.16 ,   0.58 ,   9.8  ,   6.   ])

In [15]:
alcohols[:,:]


array([[  7.4  ,   0.7  ,   0.   , ...,   0.56 ,   9.4  ,   5.   ],
       [  7.8  ,   0.88 ,   0.   , ...,   0.68 ,   9.8  ,   5.   ],
       [  7.8  ,   0.76 ,   0.04 , ...,   0.65 ,   9.8  ,   5.   ],
       ..., 
       [  6.3  ,   0.51 ,   0.13 , ...,   0.75 ,  11.   ,   6.   ],
       [  5.9  ,   0.645,   0.12 , ...,   0.71 ,  10.2  ,   5.   ],
       [  6.   ,   0.31 ,   0.47 , ...,   0.66 ,  11.   ,   6.   ]])

In [16]:
alcohols[1,5] = 10


In [17]:
alcohols[:,10] = 50


In [18]:
third_alcohol = alcohols[3,:]


In [19]:
third_alcohol

array([ 11.2  ,   0.28 ,   0.56 ,   1.9  ,   0.075,  17.   ,  60.   ,
         0.998,   3.16 ,   0.58 ,  50.   ,   6.   ])

In [20]:
third_alcohol[1]


0.28000000000000003

In [21]:
np.random.rand(3)


array([ 0.03102658,  0.68798722,  0.48966841])

In [22]:
year_one = [
    [500,505,490],
    [810,450,678],
    [234,897,430],
    [560,1023,640]
]

In [23]:
earnings = [
            [
                [500,505,490],
                [810,450,678],
                [234,897,430],
                [560,1023,640]
            ],
            [
                [600,605,490],
                [345,900,1000],
                [780,730,710],
                [670,540,324]
            ]
          ]

In [24]:
earnings.shape

AttributeError: 'list' object has no attribute 'shape'

In [25]:
earnings = np.array(earnings)
earnings[0,0,0]


500

In [26]:
earnings.shape

(2, 4, 3)

In [27]:
earnings.shape


(2, 4, 3)

In [28]:
earnings[:,0,0]


array([500, 600])

In [29]:
earnings[:,0,:]


array([[500, 505, 490],
       [600, 605, 490]])

In [30]:
alcohols.dtype


dtype('float64')

In [31]:
alcohols.astype(int)


array([[ 7,  0,  0, ...,  0, 50,  5],
       [ 7,  0,  0, ...,  0, 50,  5],
       [ 7,  0,  0, ...,  0, 50,  5],
       ..., 
       [ 6,  0,  0, ...,  0, 50,  6],
       [ 5,  0,  0, ...,  0, 50,  5],
       [ 6,  0,  0, ...,  0, 50,  6]])

In [32]:
int_alcohols = alcohols.astype(int)
int_alcohols.dtype.name

'int64'

In [33]:
alcohols.astype(np.int32)

array([[ 7,  0,  0, ...,  0, 50,  5],
       [ 7,  0,  0, ...,  0, 50,  5],
       [ 7,  0,  0, ...,  0, 50,  5],
       ..., 
       [ 6,  0,  0, ...,  0, 50,  6],
       [ 5,  0,  0, ...,  0, 50,  5],
       [ 6,  0,  0, ...,  0, 50,  6]], dtype=int32)

NumPy Array Operations


In [34]:
alcohols[:,11] + 10
#Broadcasting

array([ 15.,  15.,  15., ...,  16.,  15.,  16.])

In [35]:
alcohols[:,11] += 10
alcohols[:,11]

array([ 15.,  15.,  15., ...,  16.,  15.,  16.])

In [36]:
alcohols[:,11] * 2


array([ 30.,  30.,  30., ...,  32.,  30.,  32.])

In [37]:
alcohols[:,11] + alcohols[:,11]


array([ 30.,  30.,  30., ...,  32.,  30.,  32.])

In [38]:
alcohols[:,10] * alcohols[:,11]


array([ 750.,  750.,  750., ...,  800.,  750.,  800.])

In [39]:
alcohols * np.array([1,2])


ValueError: operands could not be broadcast together with shapes (1599,12) (2,) 

In [40]:
array_one = np.array(
    [
        [1,2],
        [3,4]
    ]
)
array_two = np.array([4,5])

array_one + array_two

array([[5, 7],
       [7, 9]])

In [41]:
rand_array = np.random.rand(12)
alcohols + rand_array

array([[  7.47695786,   1.08552828,   0.33638936, ...,   0.68311711,
         50.01418729,  15.12730811],
       [  7.87695786,   1.26552828,   0.33638936, ...,   0.80311711,
         50.01418729,  15.12730811],
       [  7.87695786,   1.14552828,   0.37638936, ...,   0.77311711,
         50.01418729,  15.12730811],
       ..., 
       [  6.37695786,   0.89552828,   0.46638936, ...,   0.87311711,
         50.01418729,  16.12730811],
       [  5.97695786,   1.03052828,   0.45638936, ...,   0.83311711,
         50.01418729,  15.12730811],
       [  6.07695786,   0.69552828,   0.80638936, ...,   0.78311711,
         50.01418729,  16.12730811]])

In [42]:
alcohols[:,11].sum()
len(alcohols[:,11])
alcohols[:,11].mean()


15.636022514071295

In [43]:
alcohols.sum(axis=0)
#alcohols.shape

array([ 13303.1    ,    843.985  ,    433.29   ,   4059.55   ,
          139.859  ,  25369.     ,  74302.     ,   1593.79794,
         5294.47   ,   1052.38   ,  79950.     ,  25002.     ])

In [44]:
alcohols.sum(axis=1).shape


(1599,)

In [45]:
alcohols.sum(axis=1)


array([ 125.1438 ,  158.2548 ,  149.899  , ...,  149.48174,  155.01547,
        141.49249])

In [46]:
alcohols[:,11] > 5


array([ True,  True,  True, ...,  True,  True,  True], dtype=bool)

In [47]:
alcohols[:,11] == 10


array([False, False, False, ..., False, False, False], dtype=bool)

Subsetting


In [48]:
high_quality = alcohols[:,11] == 6


In [49]:
high_quality

array([False, False, False, ..., False, False, False], dtype=bool)

In [50]:
alcohols[high_quality,:]

array([], shape=(0, 12), dtype=float64)

In [51]:
high_quality = alcohols[:,11] > 7
alcohols[high_quality,:][:3,:]

array([[  7.40000000e+00,   7.00000000e-01,   0.00000000e+00,
          1.90000000e+00,   7.60000000e-02,   1.10000000e+01,
          3.40000000e+01,   9.97800000e-01,   3.51000000e+00,
          5.60000000e-01,   5.00000000e+01,   1.50000000e+01],
       [  7.80000000e+00,   8.80000000e-01,   0.00000000e+00,
          2.60000000e+00,   9.80000000e-02,   1.00000000e+01,
          6.70000000e+01,   9.96800000e-01,   3.20000000e+00,
          6.80000000e-01,   5.00000000e+01,   1.50000000e+01],
       [  7.80000000e+00,   7.60000000e-01,   4.00000000e-02,
          2.30000000e+00,   9.20000000e-02,   1.50000000e+01,
          5.40000000e+01,   9.97000000e-01,   3.26000000e+00,
          6.50000000e-01,   5.00000000e+01,   1.50000000e+01]])

In [52]:
(alcohols[:,10] > 10) & (alcohols[:,11] > 7)

array([ True,  True,  True, ...,  True,  True,  True], dtype=bool)

In [53]:
a = np.array([[1,2,3],[4,5,6]])

In [54]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
a[([True,True]),0:2]

array([[1, 2],
       [4, 5]])

In [56]:
high_quality_and_alcohol = (alcohols[:,10] > 10) & (alcohols[:,11] > 7)
alcohols[high_quality_and_alcohol,10:]

array([[ 50.,  15.],
       [ 50.,  15.],
       [ 50.,  15.],
       ..., 
       [ 50.,  16.],
       [ 50.,  15.],
       [ 50.,  16.]])

In [57]:
high_quality_and_alcohol = (alcohols[:,10] > 10) & (alcohols[:,11] > 7)


In [58]:
high_quality_and_alcohol.shape

(1599,)

In [59]:
high_quality_and_alcohol[10:40]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True], dtype=bool)

In [60]:
high_quality_and_alcohol = (alcohols[:,10] > 10) & (alcohols[:,11] > 7)
alcohols[high_quality_and_alcohol,10:] 

array([[ 50.,  15.],
       [ 50.,  15.],
       [ 50.,  15.],
       ..., 
       [ 50.,  16.],
       [ 50.,  15.],
       [ 50.,  16.]])

In [61]:
np.transpose(alcohols).shape


(12, 1599)

In [62]:
alcohols.ravel().shape


(19188,)

In [63]:
array_one = np.array(
    [
        [1, 2, 3, 4], 
        [5, 6, 7, 8]
    ]
)

array_one.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
alcohols[1,:].reshape((2,6))


array([[  7.8   ,   0.88  ,   0.    ,   2.6   ,   0.098 ,  10.    ],
       [ 67.    ,   0.9968,   3.2   ,   0.68  ,  50.    ,  15.    ]])

In [74]:
white_alcohols = np.genfromtxt("alcoholquality-white.csv", delimiter=";", skip_header=1)
white_alcohols.shape

(4898, 12)

In [71]:
np.vstack?

In [72]:
all_alcohols = np.vstack((alcohols, white_alcohols))
all_alcohols.shape

(6497, 12)

In [73]:
np.concatenate((alcohols, white_alcohols), axis=0)


array([[  7.40000000e+00,   7.00000000e-01,   0.00000000e+00, ...,
          5.60000000e-01,   5.00000000e+01,   1.50000000e+01],
       [  7.80000000e+00,   8.80000000e-01,   0.00000000e+00, ...,
          6.80000000e-01,   5.00000000e+01,   1.50000000e+01],
       [  7.80000000e+00,   7.60000000e-01,   4.00000000e-02, ...,
          6.50000000e-01,   5.00000000e+01,   1.50000000e+01],
       ..., 
       [  6.50000000e+00,   2.40000000e-01,   1.90000000e-01, ...,
          4.60000000e-01,   9.40000000e+00,   6.00000000e+00],
       [  5.50000000e+00,   2.90000000e-01,   3.00000000e-01, ...,
          3.80000000e-01,   1.28000000e+01,   7.00000000e+00],
       [  6.00000000e+00,   2.10000000e-01,   3.80000000e-01, ...,
          3.20000000e-01,   1.18000000e+01,   6.00000000e+00]])